version: 0.2

phases:
  install:
    commands:
      - echo runing yarn install...
      - yarn
  pre_build:
    commands:
      - echo started at `date`
  build:
    commands:
      - echo Build started on `date`
      - yarn build
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPOSITORY_URI:$NODE_ENV
      - echo Changing the Dockerrun file to the correct for this environment
      - sed -i 's/DUMMY_ENV/'$NODE_ENV'/g' Dockerrun.aws.json
artifacts:
  files:
    - .next/**/*
    - public/**/*
    - .ebextenstions/**/*
    - package.json


